/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.$runtime.getProperty("tigerstripe.feature.version")
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package CoreModel.CoreFoundationModule.StateModel.TypeDefinitions;


/**
 * The possible values of the administrativeState.
 *
 * @tigerstripe.enum
 *		isAbstract = "false"
 *      base-type="String"
 *      extensible="false"
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("package")"
 *      generate = "true"
 *
 * @tigerstripe.stereotype st.name = "Preliminary"
 * 
 */
public abstract class AdministrativeState
 {


    /**
     * 
     * @tigerstripe.label
     *  value = '"LOCKED"'
     *  
     *
     * 
     */
    public final static String LOCKED = "LOCKED";


    /**
     * 
     * @tigerstripe.label
     *  value = '"UNLOCKED"'
     *  
     *
     * 
     */
    public final static String UNLOCKED = "UNLOCKED";

}