/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.$runtime.getProperty("tigerstripe.feature.version")
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package CoreModel.CoreFoundationModule.StateModel.TypeDefinitions;


/**
 * The possible values of the current target administrative state.
 *
 * @tigerstripe.enum
 *		isAbstract = "false"
 *      base-type="String"
 *      extensible="false"
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("package")"
 *      generate = "true"
 *
 * @tigerstripe.stereotype st.name = "Experimental"
 * 
 */
public abstract class AdministrativeControl
 {


    /**
     * 
     * @tigerstripe.label
     *  value = '"UNLOCK"'
     *  
     *
     * 
     */
    public final static String UNLOCK = "UNLOCK";


    /**
     * 
     * @tigerstripe.label
     *  value = '"LOCK_PASSIVE"'
     *  
     *
     * 
     */
    public final static String LOCK_PASSIVE = "LOCK_PASSIVE";


    /**
     * 
     * @tigerstripe.label
     *  value = '"LOCK_ACTIVE"'
     *  
     *
     * 
     */
    public final static String LOCK_ACTIVE = "LOCK_ACTIVE";


    /**
     * 
     * @tigerstripe.label
     *  value = '"LOCK_IMMEDIATE"'
     *  
     *
     * 
     */
    public final static String LOCK_IMMEDIATE = "LOCK_IMMEDIATE";

}