/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.$runtime.getProperty("tigerstripe.feature.version")
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package CoreModel.CoreFoundationModule.StateModel.TypeDefinitions;


/**
 * Possible extentions to AdministrativeState
 *
 * @tigerstripe.enum
 *		isAbstract = "false"
 *      base-type="String"
 *      extensible="false"
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("
 *      generate = "true"
 *
 * @tigerstripe.stereotype st.name = "Experimental"
 * 
 */
public abstract class ExtendedAdminState
  extends CoreModel.CoreFoundationModule.StateModel.TypeDefinitions.AdministrativeState
 {


    /**
     * 
     * @tigerstripe.label
     *  value = '"SHUTTING_DOWN_ACTIVE"'
     *  
     *
     * 
     */
    public final static String SHUTTING_DOWN_ACTIVE = "SHUTTING_DOWN_ACTIVE";


    /**
     * 
     * @tigerstripe.label
     *  value = '"SHUTTING_DOWN_PASSIVE"'
     *  
     *
     * 
     */
    public final static String SHUTTING_DOWN_PASSIVE = "SHUTTING_DOWN_PASSIVE";

}