/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.$runtime.getProperty("tigerstripe.feature.version")
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package NRP_Interface.TypeDefinitions.NRP_Types;


/**
 * Layer 2 Control Protocol address set.
 *
 * @tigerstripe.enum
 *		isAbstract = "false"
 *      base-type="String"
 *      extensible="false"
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("package")"
 *      generate = "true"
 * * 
 */
public abstract class NRP_L2cpAddressSet
 {


    /**
     * 
     * @tigerstripe.label
     *  value = '"CTA"'
     *  
     *
     * 
     */
    public final static String CTA = "CTA";


    /**
     * 
     * @tigerstripe.label
     *  value = '"CTB"'
     *  
     *
     * 
     */
    public final static String CTB = "CTB";


    /**
     * 
     * @tigerstripe.label
     *  value = '"CTB2"'
     *  
     *
     * 
     */
    public final static String CTB2 = "CTB2";

}