/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.$runtime.getProperty("tigerstripe.feature.version")
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package NRP_Interface.TypeDefinitions.NRP_Types;


/**
 * IEEE802.3 (2012) defined list excluding 1000BASE-PX-D and 1000BASE-PX-U. NONE is added with further MEF 10.3 discussion, for supporting logical interfaces.
 *
 * @tigerstripe.enum
 *		isAbstract = "false"
 *      base-type="String"
 *      extensible="false"
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("package")"
 *      generate = "true"
 * * 
 */
public abstract class NRP_PhysicalLayer
 {


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10BASE2"'
     *  
     *
     * 
     */
    public final static String _10BASE2 = "_10BASE2";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10BASE5"'
     *  
     *
     * 
     */
    public final static String _10BASE5 = "_10BASE5";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10BASE_F"'
     *  
     *
     * 
     */
    public final static String _10BASE_F = "_10BASE_F";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10BASE_FB"'
     *  
     *
     * 
     */
    public final static String _10BASE_FB = "_10BASE_FB";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10BASE_FL"'
     *  
     *
     * 
     */
    public final static String _10BASE_FL = "_10BASE_FL";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10BASE_FP"'
     *  
     *
     * 
     */
    public final static String _10BASE_FP = "_10BASE_FP";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10BASE_T"'
     *  
     *
     * 
     */
    public final static String _10BASE_T = "_10BASE_T";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10BASE_TE"'
     *  
     *
     * 
     */
    public final static String _10BASE_TE = "_10BASE_TE";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10BROAD36"'
     *  
     *
     * 
     */
    public final static String _10BROAD36 = "_10BROAD36";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10PASS_TS"'
     *  
     *
     * 
     */
    public final static String _10PASS_TS = "_10PASS_TS";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_100BASE_BX10"'
     *  
     *
     * 
     */
    public final static String _100BASE_BX10 = "_100BASE_BX10";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_100BASE_FX"'
     *  
     *
     * 
     */
    public final static String _100BASE_FX = "_100BASE_FX";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_100BASE_LX10"'
     *  
     *
     * 
     */
    public final static String _100BASE_LX10 = "_100BASE_LX10";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_100BASE_T"'
     *  
     *
     * 
     */
    public final static String _100BASE_T = "_100BASE_T";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_100BASE_T2"'
     *  
     *
     * 
     */
    public final static String _100BASE_T2 = "_100BASE_T2";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_100BASE_T4"'
     *  
     *
     * 
     */
    public final static String _100BASE_T4 = "_100BASE_T4";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_100BASE_TX"'
     *  
     *
     * 
     */
    public final static String _100BASE_TX = "_100BASE_TX";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_100BASE_X"'
     *  
     *
     * 
     */
    public final static String _100BASE_X = "_100BASE_X";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_1000BASE_BX10"'
     *  
     *
     * 
     */
    public final static String _1000BASE_BX10 = "_1000BASE_BX10";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_1000BASE_CX"'
     *  
     *
     * 
     */
    public final static String _1000BASE_CX = "_1000BASE_CX";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_1000BASE_KX"'
     *  
     *
     * 
     */
    public final static String _1000BASE_KX = "_1000BASE_KX";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_1000BASE_LX"'
     *  
     *
     * 
     */
    public final static String _1000BASE_LX = "_1000BASE_LX";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_1000BASE_LX10"'
     *  
     *
     * 
     */
    public final static String _1000BASE_LX10 = "_1000BASE_LX10";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_1000BASE_PX10"'
     *  
     *
     * 
     */
    public final static String _1000BASE_PX10 = "_1000BASE_PX10";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_1000BASE_PX20"'
     *  
     *
     * 
     */
    public final static String _1000BASE_PX20 = "_1000BASE_PX20";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_1000BASE_SX"'
     *  
     *
     * 
     */
    public final static String _1000BASE_SX = "_1000BASE_SX";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_1000BASE_T"'
     *  
     *
     * 
     */
    public final static String _1000BASE_T = "_1000BASE_T";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_1000BASE_X"'
     *  
     *
     * 
     */
    public final static String _1000BASE_X = "_1000BASE_X";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_CX4"'
     *  
     *
     * 
     */
    public final static String _10GBASE_CX4 = "_10GBASE_CX4";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_E"'
     *  
     *
     * 
     */
    public final static String _10GBASE_E = "_10GBASE_E";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_ER"'
     *  
     *
     * 
     */
    public final static String _10GBASE_ER = "_10GBASE_ER";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_EW"'
     *  
     *
     * 
     */
    public final static String _10GBASE_EW = "_10GBASE_EW";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_KR"'
     *  
     *
     * 
     */
    public final static String _10GBASE_KR = "_10GBASE_KR";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_KX4"'
     *  
     *
     * 
     */
    public final static String _10GBASE_KX4 = "_10GBASE_KX4";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_L"'
     *  
     *
     * 
     */
    public final static String _10GBASE_L = "_10GBASE_L";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_LR"'
     *  
     *
     * 
     */
    public final static String _10GBASE_LR = "_10GBASE_LR";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_LRM"'
     *  
     *
     * 
     */
    public final static String _10GBASE_LRM = "_10GBASE_LRM";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_LW"'
     *  
     *
     * 
     */
    public final static String _10GBASE_LW = "_10GBASE_LW";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_LX4"'
     *  
     *
     * 
     */
    public final static String _10GBASE_LX4 = "_10GBASE_LX4";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_PR"'
     *  
     *
     * 
     */
    public final static String _10GBASE_PR = "_10GBASE_PR";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_PRX"'
     *  
     *
     * 
     */
    public final static String _10GBASE_PRX = "_10GBASE_PRX";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_R"'
     *  
     *
     * 
     */
    public final static String _10GBASE_R = "_10GBASE_R";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_S"'
     *  
     *
     * 
     */
    public final static String _10GBASE_S = "_10GBASE_S";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_SR"'
     *  
     *
     * 
     */
    public final static String _10GBASE_SR = "_10GBASE_SR";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_SW"'
     *  
     *
     * 
     */
    public final static String _10GBASE_SW = "_10GBASE_SW";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_T"'
     *  
     *
     * 
     */
    public final static String _10GBASE_T = "_10GBASE_T";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_W"'
     *  
     *
     * 
     */
    public final static String _10GBASE_W = "_10GBASE_W";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10GBASE_X"'
     *  
     *
     * 
     */
    public final static String _10GBASE_X = "_10GBASE_X";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_100GBASE_R"'
     *  
     *
     * 
     */
    public final static String _100GBASE_R = "_100GBASE_R";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_100GBASE_CR10"'
     *  
     *
     * 
     */
    public final static String _100GBASE_CR10 = "_100GBASE_CR10";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_100GBASE_ER4"'
     *  
     *
     * 
     */
    public final static String _100GBASE_ER4 = "_100GBASE_ER4";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_100GBASE_LR4"'
     *  
     *
     * 
     */
    public final static String _100GBASE_LR4 = "_100GBASE_LR4";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_100GBASE_SR10"'
     *  
     *
     * 
     */
    public final static String _100GBASE_SR10 = "_100GBASE_SR10";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_40GBASE_R"'
     *  
     *
     * 
     */
    public final static String _40GBASE_R = "_40GBASE_R";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_40GBASE_CR4"'
     *  
     *
     * 
     */
    public final static String _40GBASE_CR4 = "_40GBASE_CR4";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_40GBASE__FR"'
     *  
     *
     * 
     */
    public final static String _40GBASE__FR = "_40GBASE__FR";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_40GBASE_KR4"'
     *  
     *
     * 
     */
    public final static String _40GBASE_KR4 = "_40GBASE_KR4";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_40GBASE_LR4"'
     *  
     *
     * 
     */
    public final static String _40GBASE_LR4 = "_40GBASE_LR4";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_40GBASE_SR4"'
     *  
     *
     * 
     */
    public final static String _40GBASE_SR4 = "_40GBASE_SR4";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_1BASE5"'
     *  
     *
     * 
     */
    public final static String _1BASE5 = "_1BASE5";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_2BASE_TL"'
     *  
     *
     * 
     */
    public final static String _2BASE_TL = "_2BASE_TL";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_1G_EPON"'
     *  
     *
     * 
     */
    public final static String _1G_EPON = "_1G_EPON";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10G_EPON"'
     *  
     *
     * 
     */
    public final static String _10G_EPON = "_10G_EPON";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10_1G_EPON"'
     *  
     *
     * 
     */
    public final static String _10_1G_EPON = "_10_1G_EPON";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_10_10G_EPON"'
     *  
     *
     * 
     */
    public final static String _10_10G_EPON = "_10_10G_EPON";


    /**
     * 
     * @tigerstripe.label
     *  value = '"NONE"'
     *  
     *
     * 
     */
    public final static String NONE = "NONE";

}