/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.$runtime.getProperty("tigerstripe.feature.version")
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package NRP_Interface.TypeDefinitions.NRP_Types;


/**
 * Vlan Tag type, S-tag, C-tag (future B-tag, I-tag).
 *
 * @tigerstripe.enum
 *		isAbstract = "false"
 *      base-type="String"
 *      extensible="false"
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("package")"
 *      generate = "true"
 * * 
 */
public abstract class NRP_VlanTag
 {


    /**
     * 
     * @tigerstripe.label
     *  value = '"S_TAG"'
     *  
     *
     * 
     */
    public final static String S_TAG = "S_TAG";


    /**
     * 
     * @tigerstripe.label
     *  value = '"C_TAG"'
     *  
     *
     * 
     */
    public final static String C_TAG = "C_TAG";

}