/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.$runtime.getProperty("tigerstripe.feature.version")
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package NRP_Interface.TypeDefinitions.NRP_Types;


/**
 * Indicates whether the Color Identifier of the Service Frame is considered by the Bandwidth Profile Algorithm.
 *
 * @tigerstripe.enum
 *		isAbstract = "false"
 *      base-type="String"
 *      extensible="false"
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("package")"
 *      generate = "true"
 * * 
 */
public abstract class NRP_ColorMode
 {


    /**
     * 
     * @tigerstripe.label
     *  value = '"COLOR_AWARE"'
     *  
     *
     * 
     */
    public final static String COLOR_AWARE = "COLOR_AWARE";


    /**
     * 
     * @tigerstripe.label
     *  value = '"COLOR_BLIND"'
     *  
     *
     * 
     */
    public final static String COLOR_BLIND = "COLOR_BLIND";

}