/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.$runtime.getProperty("tigerstripe.feature.version")
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package NRP_Interface.TypeDefinitions.NRP_Types;


/**
 * The value indicates how external interface frames mapped to the  EVC End Point can be forwarded.
 *
 * @tigerstripe.enum
 *		isAbstract = "false"
 *      base-type="String"
 *      extensible="false"
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("package")"
 *      generate = "true"
 * * 
 */
public abstract class NRP_EndPointRole
 {


    /**
     * 
     * @tigerstripe.label
     *  value = '"ROOT"'
     *  
     *
     * 
     */
    public final static String ROOT = "ROOT";


    /**
     * 
     * @tigerstripe.label
     *  value = '"LEAF"'
     *  
     *
     * 
     */
    public final static String LEAF = "LEAF";


    /**
     * 
     * @tigerstripe.label
     *  value = '"TRUNK"'
     *  
     *
     * 
     */
    public final static String TRUNK = "TRUNK";

}