/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.$runtime.getProperty("tigerstripe.feature.version")
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package NRP_Interface.TypeDefinitions.NRP_Types;


/**
 * The method for protection, if any, against a physical link failure.
 *
 * @tigerstripe.enum
 *		isAbstract = "false"
 *      base-type="String"
 *      extensible="false"
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("package")"
 *      generate = "true"
 * * 
 */
public abstract class NRP_InterfaceResiliency
 {


    /**
     * 
     * @tigerstripe.label
     *  value = '"NONE"'
     *  
     *
     * 
     */
    public final static String NONE = "NONE";


    /**
     * 
     * @tigerstripe.label
     *  value = '"_2_LINK_ACTIVE_STANDBY"'
     *  
     *
     * 
     */
    public final static String _2_LINK_ACTIVE_STANDBY = "_2_LINK_ACTIVE_STANDBY";


    /**
     * 
     * @tigerstripe.label
     *  value = '"ALL_ACTIVE"'
     *  
     *
     * 
     */
    public final static String ALL_ACTIVE = "ALL_ACTIVE";


    /**
     * 
     * @tigerstripe.label
     *  value = '"OTHER"'
     *  
     *
     * 
     */
    public final static String OTHER = "OTHER";

}