/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.$runtime.getProperty("tigerstripe.feature.version")
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package CoreModel.CoreFoundationModule.TypeDefinitions;


/**
 * This primitive type defines the date and time according to the following structure:
&quot;yyyyMMddhhmmss.s[Z|{+|-}HHMm]&quot; where:
yyyy	&quot;0000&quot;..&quot;9999&quot;	year
MM		&quot;01&quot;..&quot;12&quot;			month
dd		&quot;01&quot;..&quot;31&quot;			day
hh		&quot;00&quot;..&quot;23&quot;			hour
mm		&quot;00&quot;..&quot;59&quot;			minute
ss		&quot;00&quot;..&quot;59&quot;			second
s		&quot;.0&quot;..&quot;.9&quot;			tenth of second (set to &quot;.0&quot; if EMS or NE cannot support this granularity)
Z		&quot;Z&quot;					indicates UTC (rather than local time)
{+|-}	&quot;+&quot; or &quot;-&quot;			delta from UTC
HH		&quot;00&quot;..&quot;23&quot;			time zone difference in hours
Mm		&quot;00&quot;..&quot;59&quot;			time zone difference in minutes.
 *
 * @tigerstripe.datatype
 *		isAbstract = "false"
 *      isSingleExtensionType="false"
 *      isSessionFactoryMethods="false"
 *		implements = ""
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("package")"
 *      generate = "true"
 * * 
 */
public abstract class DateAndTime
 {



}