/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.$runtime.getProperty("tigerstripe.feature.version")
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package NRP_Interface.TypeDefinitions;


/**
 * The directionality of a Forwarding entity.
 *
 * @tigerstripe.enum
 *		isAbstract = "false"
 *      base-type="String"
 *      extensible="false"
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("package")"
 *      generate = "true"
 * * 
 */
public abstract class ForwardingDirection
 {


    /**
     * 
     * @tigerstripe.label
     *  value = '"BIDIRECTIONAL"'
     *  
     *
     * 
     */
    public final static String BIDIRECTIONAL = "BIDIRECTIONAL";


    /**
     * 
     * @tigerstripe.label
     *  value = '"UNIDIRECTIONAL"'
     *  
     *
     * 
     */
    public final static String UNIDIRECTIONAL = "UNIDIRECTIONAL";


    /**
     * 
     * @tigerstripe.label
     *  value = '"UNDEFINED_OR_UNKNOWN"'
     *  
     *
     * 
     */
    public final static String UNDEFINED_OR_UNKNOWN = "UNDEFINED_OR_UNKNOWN";

}