/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.$runtime.getProperty("tigerstripe.feature.version")
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package CoreModel.CoreNetworkModule.TypeDefinitions;


/**
 * The orientation of flow at the Port of a Forwarding entity
 *
 * @tigerstripe.enum
 *		isAbstract = "false"
 *      base-type="String"
 *      extensible="false"
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("package")"
 *      generate = "true"
 * * 
 */
public abstract class PortDirection
 {


    /**
     * 
     * @tigerstripe.label
     *  value = '"BIDIRECTIONAL"'
     *  
     *
     * 
     */
    public final static String BIDIRECTIONAL = "BIDIRECTIONAL";


    /**
     * 
     * @tigerstripe.label
     *  value = '"INPUT"'
     *  
     *
     * 
     */
    public final static String INPUT = "INPUT";


    /**
     * 
     * @tigerstripe.label
     *  value = '"OUTPUT"'
     *  
     *
     * 
     */
    public final static String OUTPUT = "OUTPUT";


    /**
     * 
     * @tigerstripe.label
     *  value = '"UNIDENTIFIED_OR_UNKNOWN"'
     *  
     *
     * 
     */
    public final static String UNIDENTIFIED_OR_UNKNOWN = "UNIDENTIFIED_OR_UNKNOWN";

}