/*******************************************************************************
 * Created with Tigerstripe(tm) Workbench v.$runtime.getProperty("tigerstripe.feature.version")
 * Copyright (c) 2007 Cisco Systems, Inc.
 * All rights reserved. This program and the accompanying materials
 * are made available under the terms of the Eclipse Public License v1.0
 * which accompanies this distribution, and is available at
 * http://www.eclipse.org/legal/epl-v10.html
 *
 * DO NOT EDIT THIS FILE - Created with Tigerstripe(tm) Workbench
 *
 *******************************************************************************/
package CoreModel.CoreNetworkModule.TypeDefinitions;


/**
 * Provides support for the range of behaviours and specific states that an LP can take with respect to termination of the signal.
Indicates to what degree the LayerTermination is terminated.
 *
 * @tigerstripe.enum
 *		isAbstract = "false"
 *      base-type="String"
 *      extensible="false"
 * @tigerstripe.interface package = "$artifact.IStandardSpecifics.InterfaceProperties.get("package")"
 *      generate = "true"
 *
 * @tigerstripe.stereotype st.name = "Experimental"
 * 
 */
public abstract class TerminationState
 {


    /**
     * 
     * @tigerstripe.label
     *  value = '"LP_CAN_NEVER_TERMINATE"'
     *  
     *
     * 
     */
    public final static String LP_CAN_NEVER_TERMINATE = "LP_CAN_NEVER_TERMINATE";


    /**
     * 
     * @tigerstripe.label
     *  value = '"LT_NOT_TERMINATED"'
     *  
     *
     * 
     */
    public final static String LT_NOT_TERMINATED = "LT_NOT_TERMINATED";


    /**
     * 
     * @tigerstripe.label
     *  value = '"TERMINATED_SERVER_TO_CLIENT_FLOW"'
     *  
     *
     * 
     */
    public final static String TERMINATED_SERVER_TO_CLIENT_FLOW = "TERMINATED_SERVER_TO_CLIENT_FLOW";


    /**
     * 
     * @tigerstripe.label
     *  value = '"TERMINATED_CLIENT_TO_SERVER_FLOW"'
     *  
     *
     * 
     */
    public final static String TERMINATED_CLIENT_TO_SERVER_FLOW = "TERMINATED_CLIENT_TO_SERVER_FLOW";


    /**
     * 
     * @tigerstripe.label
     *  value = '"TERMINATED_BIDIRECTIONAL"'
     *  
     *
     * 
     */
    public final static String TERMINATED_BIDIRECTIONAL = "TERMINATED_BIDIRECTIONAL";


    /**
     * 
     * @tigerstripe.label
     *  value = '"LT_PERMENANTLY_TERMINATED"'
     *  
     *
     * 
     */
    public final static String LT_PERMENANTLY_TERMINATED = "LT_PERMENANTLY_TERMINATED";


    /**
     * 
     * @tigerstripe.label
     *  value = '"TERMINATION_STATE_UNKNOWN"'
     *  
     *
     * 
     */
    public final static String TERMINATION_STATE_UNKNOWN = "TERMINATION_STATE_UNKNOWN";

}